solved arellano
QuantEcon/lecture-jax pull request #32
Opened 2023-05-07 23:56 UTC by chappiewuzefan

remove np with at in jax; replace random func in jax [arellano](https://github.com/QuantEcon/lecture-jax/issues/12) (forgot to create a new branch) but this one is only changed a little bit

2023-05-07 23:58 UTC, chappiewuzefan commented
@jstac pls review (this pull request should basded on a new branch, but I forgot to create one, will remember next time for better git requests manner)

2023-05-08 00:26 UTC, jstac commented
Thanks @chappiewuzefan .

Please 

1. check failing build and
2. adjust style according to https://manual.quantecon.org/styleguide/writing.html 

(E.g., headings style.)

Feel free to reach out to other team members if you have problems.

2023-05-08 01:32 UTC, mmcky commented
@chappiewuzefan there are some warnings that need to be fixed as warnings in the GitHub context will cause the workflow to fail.

1. Broken Links

- [ ] /__w/lecture-jax/lecture-jax/lectures/arellano.md:117: WARNING: 'myst' reference target not found: #equation-utility
resolving references...
- [ ] /__w/lecture-jax/lecture-jax/lectures/arellano.md:298: WARNING: 'myst' reference target not found: #equation-epc
- [ ] /__w/lecture-jax/lecture-jax/lectures/arellano.md:298: WARNING: 'myst' reference target not found: #equation-delta
- [ ] /__w/lecture-jax/lecture-jax/lectures/arellano.md:326: WARNING: 'myst' reference target not found: #equation-bondprice
- [ ] /__w/lecture-jax/lecture-jax/lectures/arellano.md:735: WARNING: 'myst' reference target not found: #equation-delta

2. Execution Error

```
No module named 'quantecon'
ModuleNotFoundError: No module named 'quantecon'
```

so you need to install the `quantecon` package at the top of your lecture like in https://manual.quantecon.org/styleguide/code.html#code

2023-05-08 01:34 UTC, chappiewuzefan commented
> 

thank u for your help!

2023-05-08 02:55 UTC, chappiewuzefan commented
@mmcky I have installed the quantecon package at the top of the lecture, but still build failed, could you please have a look, many thanks! (I tried to make the truncated sentences into full sentences)

2023-05-08 02:58 UTC, mmcky requested changes

2023-05-08 02:58 UTC, mmcky commented on lectures/arellano.md
> +<a id='equation-utility'></a>
@chappiewuzefan this isn't how you should reference the equations instead you should use the in built equation references:

```
$$
 \mathbb E \sum_{t=0}^{\infty} \beta^t u(c_t) \tag{13.1}
 $$ (equation-utility)

2023-05-08 02:59 UTC, mmcky commented
@chappiewuzefan the execution issues are now fixed but you still have some broken references due to the way you've included markdown links rather than use equation references 

```
/__w/lecture-jax/lecture-jax/lectures/arellano.md:118: WARNING: 'myst' reference target not found: #equation-utility
/__w/lecture-jax/lecture-jax/lectures/arellano.md:299: WARNING: 'myst' reference target not found: #equation-epc
/__w/lecture-jax/lecture-jax/lectures/arellano.md:299: WARNING: 'myst' reference target not found: #equation-delta
/__w/lecture-jax/lecture-jax/lectures/arellano.md:326: WARNING: 'myst' reference target not found: #equation-bondprice
/__w/lecture-jax/lecture-jax/lectures/arellano.md:735: WARNING: 'myst' reference target not found: #equation-delta
```

there is also an example at the bottom of this page: https://manual.quantecon.org/styleguide/math.html

2023-05-08 03:20 UTC, jstac commented on lectures/arellano.md
> +This lecture computes versions of  Arellano’s  [[Are08](https://python-advanced.quantecon.org/zreferences.html#id126)]
@chappiewuzefan , this is not the right way to do citations.  Please read https://manual.quantecon.org/styleguide/references.html

2023-05-08 04:48 UTC, chappiewuzefan commented
@jstac ready for review! Thanks all for your help!! @mmcky @jstac

2023-05-08 04:55 UTC, chappiewuzefan commented
one small question is, in jupyter notebook:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/37008392/236737080-38788dd7-e047-41c1-b49e-dbaa8163bcb7.png">
but after build the lecs:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/37008392/236737180-add39518-40a0-48f6-ad14-d3eece85c8c1.png">

2023-05-08 04:56 UTC, jstac commented
Thanks @chappiewuzefan , much appreciated.

@mmcky I'll leave this with you.  Please feel free to ask @HengchengZhang to review if necessary.

It looks good to me at a quick glance, although the output of !pip install quantecon needs to be suppressed.

I'll be available again from around 7pm.

2023-05-08 05:11 UTC, chappiewuzefan commented
@HengchengZhang could you please review this one, another point is that do you know a better way to suppress the output? I looked at other lecs there is all the same but no that many outputs

2023-05-08 05:27 UTC, HengchengZhang commented
Many thanks @mmcky and @chappiewuzefan, just to confirm that we are assuming `Jax` to be installed already in these lectures?

Because my local build first failed due to I didn't install `Jax` in default `quantecon` environment.

2023-05-08 05:42 UTC, chappiewuzefan commented
> Many thanks @mmcky and @chappiewuzefan, just to confirm that we are assuming `Jax` to be installed already in these lectures?
> 
> Because my local build first failed due to I didn't install `Jax` in default `quantecon` environment.

Not so sure, in my local machine I use the default quantecon environment can successflly build the lec.
below is my pip list in quantecon:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/37008392/236742930-fed77108-0b9d-4f0b-ae96-fd578ba03cb3.png">

2023-05-08 06:10 UTC, HengchengZhang reviewed
Hi @chappiewuzefan, I've made the cell outputs hidden and fixed some minor typos.

2023-05-08 06:10 UTC, HengchengZhang commented on lectures/arellano.md
> +Because household are averse to consumption fluctuations, the government will try to smooth
```suggestion
Because households are averse to consumption fluctuations, the government will try to smooth
```

2023-05-08 06:10 UTC, HengchengZhang commented on lectures/arellano.md
> +Expressed recursively, the value of defaulting is
```suggestion
Expressed recursively, the value of default is
```

2023-05-08 06:10 UTC, HengchengZhang commented on lectures/arellano.md
> +:hide-output: false
```suggestion
:tags: [hide-output]
```

2023-05-08 06:10 UTC, HengchengZhang commented on lectures/arellano.md
> +```{code-cell} ipython3
```suggestion
```{code-cell} ipython3
:tags: [hide-output]

```

2023-05-08 06:10 UTC, HengchengZhang commented on lectures/arellano.md
> +#             in_default = False if jnp.random.rand() < model.θ else True
```suggestion
            # in_default = False if jnp.random.rand() < model.θ else True
```

2023-05-08 06:35 UTC, mmcky commented
> Many thanks @mmcky and @chappiewuzefan, just to confirm that we are assuming `Jax` to be installed already in these lectures?
> 
> Because my local build first failed due to I didn't install `Jax` in default `quantecon` environment.

@HengchengZhang you need to manage the `jax` package yourself if you want to build locally as per https://manual.quantecon.org/styleguide/code.html#jax

2023-05-08 06:37 UTC, mmcky commented
thanks @HengchengZhang and @chappiewuzefan. I will merge this once the CI passes.

2023-05-08 06:58 UTC, merged